version: "3.9"
services:
    webapi:
        build: ./Goiabeira_WebApi/
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Goiabeira007"
            ACCEPT_EULA: "Y"