version: "3.9"
services:
    web:
        build: ./Goiabinha_API_Core/
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
        SA_PASSWORD: "12as$goia!"
        ACCEPT_EULA: "Y"
            ports:
        - "1433:1433"